version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysql_covid
    environment:
      # je créer un utilisateur et un mdp
      - MYSQL_ROOT_PASSWORD=exemple
      # autre écriture
      # MYSQL_ROOT_PASSWORD : root
      - MYSQL_DATABASE=vaccinations
    volumes:
      # - db:/var/lib/mysql
      # Pour lier avec le service volume, je mets son nom (pas le name)
      - /mysqldb:/var/lib/mysql
      # Pour importer directement la database
      - ./data/vaccination.sql:/docker-entrypoint-initdb.d/vaccination.sql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - mysql_network

  # Service pour administrer les bd, si pas à l'aise
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mysql_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "80:3000"
    environment:
      - GRAFANA_ADMIN_USER=admin
      - GRAFANA_ADMIN_PASSWORD=admin
    networks:
      - mysql_network
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  # nom du volume ext qui sera appelé dans les autres volumes
  mysql-db:
    # nom du volume interne, je peux mettre ce que je veux, mais par convention, c'est le même :
    name: mysqldb
  grafana-storage:
    name: grafana-storage

networks:
  mysql_network:
    name: mysql_network